file_paths:
  input: data/input/input_reports.csv
rag:
  enabled: true
models:
  llm_models:
    - llama3:latest
embedding_models:
  - all-MiniLM-L6-v2
retriever:
  types:
    - vectorstore
  use_reranker: true
prompting:
  simple_prompting: true
  fewshots_method: true
  fewshots_with_NR_method: false
  fewshots_with_NR_extended_method: false
output:
  json_format: true
sampling:
  temperatures:
    - 0.1
  top_ks:
    - 40
  top_ps:
    - 0.9
processing:
  batch_size: 1
  process_all: false
  verbose: false
  timeout_duration: 10
evaluation:
  target_variable: "BTFU Score (Updated)"
  valid_values:
    - "0"
    - "1"
    - "1a"
    - "1b"
    - "2"
    - "2a"
    - "2b"
    - "3"
    - "3a"
    - "3b"
    - "3c"
    - "4"
    - "NR"
column_name_format: "{target_variable}_model_({model})_rag_enabled_({rag})_embeddings_({embeddings})_retriever_({retriever})_reranker_({reranker})_simple_prompting_({simple})_fewshots_method_({fewshots})_fewshots_with_NR_method_({nr})_fewshots_with_NR_extended_({nr_extended})_json_({json})_temp_({temp})_top_k_({top_k})_top_p_({top_p})"